"""Central configuration for deterministic FeatureExtractor scoring."""

# Business trust
BUSINESS_TRUST_VERIFIED_WEIGHT = 0.4
BUSINESS_TRUST_DOMAIN_MATCH_WEIGHT = 0.3
BUSINESS_TRUST_ACCOUNT_AGE_WEIGHT = 0.2
BUSINESS_TRUST_REPORTS_PENALTY_WEIGHT = 0.1
BUSINESS_TRUST_ACCOUNT_AGE_NORMALIZER_DAYS = 365.0
BUSINESS_TRUST_REPORTS_NORMALIZER = 10.0

# Historical engagement
HISTORICAL_ENGAGEMENT_OPENED_WEIGHT = 0.4
HISTORICAL_ENGAGEMENT_REPLIED_WEIGHT = 0.6
HISTORICAL_ENGAGEMENT_COLD_START_SCORE = 0.5

# Relationship strength
RELATIONSHIP_OPENED_WEIGHT = 0.4
RELATIONSHIP_REPLIED_WEIGHT = 0.6
RELATIONSHIP_ADMIN_BONUS = 0.2
RELATIONSHIP_COLD_START_ADMIN_SCORE = 0.2

# Sender trust
SENDER_TRUST_DENOMINATOR_SMOOTHING = 1

# Forward risk
FORWARD_HIGH_RISK_THRESHOLD = 5

# Promotion
PROMOTION_KEYWORD_WEIGHT = 0.35
PROMOTION_KEYWORD_SCORE_CAP = 0.7
PROMOTION_RETAIL_CATEGORY_WEIGHT = 0.3

# Spam risk
SPAM_REPORTS_NORMALIZER = 10.0
SPAM_REPORT_SCORE_CAP = 0.6
SPAM_HIGH_FORWARD_WEIGHT = 0.4
SPAM_LOW_FORWARD_WEIGHT = 0.2

# Scam risk
SCAM_KEYWORD_WEIGHT = 0.4
SCAM_KEYWORD_SCORE_CAP = 0.8
SCAM_UNVERIFIED_PENALTY = 0.2
SCAM_VERIFIED_BUSINESS_MULTIPLIER = 0.5
